version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  test:
    executor:
      name: node/default
      tag: "13.14" # You could specify the node version via the docker image.
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - store_artifacts:
          path: coverage
workflows:
  test_my_app:
    jobs:
      - test