version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  test:
    executor:
      name: node/default
      tag: "14.17.5"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - store_artifacts:
          path: coverage
workflows:
  build_test_publish:
    jobs:
      - test